backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/ProjectsController.php
<?php

namespace frontend\controllers;

use app\models\Attr;
use app\models\File;
use app\models\Lexem;
use app\models\Rule;
use frontend\models\FileRecord;
use frontend\utils\RulesManager;
use frontend\utils\SchemeImageManager;
use \Yii;
use frontend\models\Project;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ProjectsController implements the CRUD actions for Project model.
 */
class ProjectsController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
    
    protected function getPath($id) {
        return \Yii::getAlias('@webroot').'/uploads/'.$id;
    }

    /**
     * Lists all Project models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Project::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Project model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $path = $this->getPath($id);
        $notCached = \Yii::$app->request->get("notCached");
        if( ! $notCached) {
            $rules = (file_exists($path))
                ? (new RulesManager())->loadRules($id)
                :  $this->getActualRules();
        }
        else {
            $rules = $this->getActualRules();
        }
        $image = file_exists($path.'/scheme.png') ? Yii::getAlias('@web/uploads/'.$id.'/scheme.png') : '';
        return $this->render('view', [
            'model' => $this->findModel($id),
            'attrs' => Attr::findAll([]),
            'lexems' => $rules,
            'rules' => Rule::findAll([]),
            'schemeImage' => $image
        ]);
    }

    public function getActualRules() {
        return Lexem::find()
            ->with('rules')
            ->with('attrs')
            ->asArray()
            ->all() ;
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Project();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Project model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionBindScheme($id){
        if(!$project = $this->findModel($id)) {
            return $this->jsonBadResponseObj('model not found');
        };
        $project->formula = Yii::$app->request->post('formula');
        if (!$project->save()) {
            return  $this->jsonBadResponseObj("fail", $project->getErrors());
        }
        $rules = Lexem::find()->with('rules')->with('attrs')->asArray()->all();
       (new RulesManager())->saveRules($rules, $project->id);
       return $this->jsonResponseObj(200);
    }

    
    public function actionLoadFile($id)//@todo think about using tmp file
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $fileRecord = new FileRecord();
        $fileRecord->name = 'scheme';
        $fileRecord->ext = 'png';
        $fileRecord->project_id = $id;
        $path = \Yii::getAlias('@webroot').'/uploads/'.$id;
        if(!file_exists($path)) {
            mkdir($path);
        }
        
        $fileObj = UploadedFile::getInstancesByName("inputsfile");
        $file = new File();
        $file->uploadImageFile($fileObj,$path, 'scheme.png');
        return $this->jsonResponseObj("success", ["result" => $fileRecord->save()]);
    }


    public function actionBindSchemeImage($id){
        if(!$project = $this->findModel($id)) {
            return $this->jsonBadResponseObj('model not found');
        };
        $file = Yii::$app->request->post('file');
        $project->attrs =  Yii::$app->request->post('collected');
        (new SchemeImageManager())->saveImage($file, $id);
        return($project->save())
            ? $this->jsonResponseObj(200)
            : $this->jsonBadResponseObj("fail", $project->getErrors());
    }
    /**
     * Finds the Project model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Project the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Project::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    
    public function actionSaveExperience($id) {
        if(!$project = $this->findModel($id)) {
            return $this->jsonBadResponseObj('model not found');
        };
        $exp = [
            'attrs' => json_decode(Yii::$app->request->post('attrs')),
            'solution' => Yii::$app->request->post('solution')
        ];

        $path = \Yii::getAlias('@webroot').'/uploads/'.$id;
        if(!file_exists($path)) {
            mkdir($path);
        }
        if(!file_exists($path.'/solutions.json')) {
            file_put_contents($path.'/solutions.json', json_encode(['sol' => [$exp]], JSON_UNESCAPED_UNICODE));
        }
        else {
            $sols = json_decode(file_get_contents($path.'/solutions.json'), true);
            $sols['sol'][] = $exp;
            file_put_contents($path.'/solutions.json', json_encode($sols,JSON_UNESCAPED_UNICODE));
        }
        return $this->jsonResponseObj('success');
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use app\models\Attr;
use app\models\File;
use app\models\Lexem;
use app\models\Rule;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'index'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                        'denyCallback' => function() {
                            Yii::$app->getResponse()->redirect('site/login');
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionLoadFile($id)//@todo think about using tmp file
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $file = new File();
        $fileObj = UploadedFile::getInstancesByName("inputsfile");
        $webRoot = Yii::getAlias('@webroot')."/images";
        $path = $file->uploadImageFile($fileObj,$webRoot);
        $lexem = Lexem::findOne(["id"=>$id]);
        $lexem->image = $path;
        return ($lexem->save()) ? [ 'file' => $path ] : '';
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->redirect(['projects/index']);

        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this  \yii\web\View */
$this->title = 'Diit';
$this->registerJsFile('@web/js/arbor/lib/arbor.js',['depends'=>'frontend\assets\AppAsset']);

$this->registerJsFile('@web/js/core.js',['depends'=>'frontend\assets\AppAsset']);

$this->registerJsFile('@web/js/vue.js', ['position'=>\yii\web\View::POS_HEAD]);

$this->registerJsFile('@web/js/plugins/canvas-to-blob.min.js',['depends'=>'frontend\assets\AppAsset']);
$this->registerJsFile('@web/js/plugins/sortable.min.js',['depends'=>'frontend\assets\AppAsset']);
$this->registerJsFile('@web/js/plugins/purify.min.js',['depends'=>'frontend\assets\AppAsset']);
$this->registerJsFile('@web/js/fileinput.min.js',['depends'=>'frontend\assets\AppAsset']);
$this->registerJsFile('@web/js/locales/ru.js',['depends'=>'frontend\assets\AppAsset']);

$this->registerCssFile('@web/css/fileinput.min.css',['depends'=>'frontend\assets\AppAsset']);


?>
<style>
    #create-proj {
        margin:10px;
    }
</style>
<pre><?php

?>
    </pre>
<script>
    var lexemArray = {};
    var lexemIds = {};
    var currentName = '';
    var lexemsData = {};
<?php

for ($i = 0, $size = count($lexems); $i < $size; $i++):?>
    <?php $current = $lexems[$i]; ?>
    lexemsData[<?=$current['id']?>] = JSON.parse('<?=json_encode($current)?>');
    currentName = '<?=$current['name']?>';
    lexemArray[currentName] = [];
    <?php for ($j = 0, $sizeRules = count($current['rules']); $j < $sizeRules; $j++):?>
    lexemArray[currentName].push('<?=$current['rules'][$j]['body']?>');
    <?php endfor;?>
    lexemIds[currentName] = <?=$lexems[$i]['id']?>;
<?php endfor;
?>

</script>


<div class="site-index">
    <div class="container-fluid">
        <div class="row">
            <?=$this->render('parts/status-panel'); ?>
            <div class="col-md-9 col-md-offset-2" id="contentLogs">
                <ul class="nav nav-tabs" id="contentTabs" role="tablist" >
                    <li id="Project" role="presentation" class="active"><a href="#project" aria-controls="mse" role="tab" data-toggle="tab">Проекти</a></li>
                    <li id="MetaSearchEngine" role="presentation"><a href="#mse" aria-controls="mse" role="tab" data-toggle="tab">Правила</a></li>
                    <li id="StateTabLink" role="presentation" ><a href="#mc" aria-controls="mc" role="tab" data-toggle="tab">Стан</a></li>
                    <li id="operations" role="presentation" ><a href="#ops" aria-controls="ops" role="tab" data-toggle="tab">Операції</a></li>
                    <li id="attribs" role="presentation" ><a href="#attrs" aria-controls="attrs" role="tab" data-toggle="tab">Атрибути</a></li>
                    <li id="Statistic" role="presentation"><a href="#statistic" aria-controls="statistic" role="tab" data-toggle="tab">Схема</a></li>
                </ul>
                <div class="loader"></div>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="project">
                        <div id="create-proj">
                            <?= \yii\helpers\Html::button('Додати проект', ['class' => 'btn btn-success', 'onclick' => 'location.href="/projects/create";']) ?>
                        </div>

                        <?= \yii\grid\GridView::widget([
                            'dataProvider' => new \yii\data\ActiveDataProvider([
                                'query' => \frontend\models\Project::find(),
                                'sort'=> ['defaultOrder' => ['created_at' => SORT_ASC]],
                                'pagination' => [
                                    'pageSize' => 20,
                                ],
                            ]),
                            'summary' => false,
                            'columns' => [
                                'title',
                                [
                                    'attribute' => 'created_at',
                                    'format' => ['date', 'php:Y-m-d H:m:s']
                                ],

                                [
                                    'headerOptions' => ['style' => 'width: 70px;'],
                                    'contentOptions' => ['style' => 'text-align: center'],
                                    'class' => 'yii\grid\ActionColumn',
                                    'template' => '{update} {delete}',
                                    'buttons' => [
                                        'update' => function($url, $model) {
                                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-pencil"></span>',
                                                '/projects/update?id='.$model->id,
                                                ['title' => "Редагувати", 'data-pjax' => '0']);

                                        },
                                        'delete' => function($url, $model) {
                                            return \yii\helpers\Html::a( '<span class="glyphicon glyphicon-trash"></span>',
                                                '/projects/delete?id='.$model->id,
                                                ['title' => Yii::t('yii', 'View'), 'data-pjax' => '1','data-method'=>'POST']);

                                        }
                                    ]
                                ],
                            ],
                        ]); ?>



                    </div>
                    <div role="tabpanel" class="tab-pane" id="mse">

                        <?=$this->render('parts/lexems-table');?>

                    </div>
                    <div role="tabpanel" class="tab-pane" id="mc">
                        <pre><code class="language-json logs-result" id="stateResult"></code></pre>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="ops">
                        <table id="opsTable" class="table table-hover">
                            <thead>
                            <tr>
                                <th>Операція</th>
                                <th>Опис</th>
                                <th>Позначення на схемі</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr><td>+</td><td>Послідовне з'єднання</td><td></td></tr>
                            <tr><td>:</td><td>Паралельне з'єднання</td><td></td></tr>
                            <tr><td>*</td><td>Розгалудження</td><td></td></tr>
                            <tr><td>(</td><td>-</td><td>-</td></tr>
                            <tr><td>)</td><td>-</td><td>-</td></tr>
                            </tbody>
                        </table>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="attrs">

                        <?=$this->render('parts/attrs-table');?>

                    </div>
                    <div role="tabpanel" class="tab-pane" id="statistic">
                        <div class="input-group">
                            <input type="text" class="form-control" id="schemeCode" value="">
                            <span class="input-group-btn">
                                <button class="btn btn-default buildScheme" type="button">
                                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Виконати
                                </button>
                                <button class="btn btn-default bootstrapScheme" type="button">
                                    <span class="glyphicon glyphicon-repeat" aria-hidden="true"></span> Розгорнути
                                </button>
                            </span>
                        </div>
                        <p id="errorScheme" class="text-danger"></p>
                        <canvas id="viewport" width="600" height="400"></canvas>
                    </div>
                </div>
            </div>
            <?=$this->render('parts/work-panel'); ?>
        </div>
    </div>
</div>

<?=$this->render('popups/send-attr'); ?>
<?=$this->render('popups/send-lexem'); ?>
<?=$this->render('popups/send-image'); ?>
<?=$this->render('popups/send-rule'); ?>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Увійти';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Перед тим, як використовувати програму, необхідно авторизуватись або <?= Html::a('зареєструватись', ['site/signup'])?> </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    Якщо ви забули пароль, ви можете <?= Html::a('відновити його', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Увійти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Реєстрація';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Заповніть наступні поля:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Зареєструватись', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>